### ISSUE TITLE
The project does not work on VSCode version 1.17

### ISSUE THREAD

**Issue by rugpanov** [kieferrm/vscode-keytar-sample#1]
@kieferrm, hi! At first, thank you for your great example of using the keytar module.
I've packaged one of the projects via `vsce package` and tested them on VS Code Insiders and on release version of VSCode 1.17. And the provided example works on VS Code Insiders but not on release version of VSCode. There is a strange error `%1 is not a valid Win32 application` there. Do you have any ideas why it's so?

**Comment by kieferrm** [comment]
@rugpanov I updated the project with a couple of additional pieces of information. Such as how to find the right electron version that a certain version of VS Code uses and how to specify the version, i.e. either in the `extensions/.yarnrc` file or in the npm command line.  Hope that helps.
